// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcibkpxhyivgfvrojrbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjaWJrcHhoeWl2Z2Z2cm9qcmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzkzMzUsImV4cCI6MjA2NzY1NTMzNX0.lCrwV5ZeCaJt5vlDYYgt39MAcivxaMyrUnlEcf3U9Zw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});